### PR TITLE
Fix moq for go 1.13 and avoid creating empty directory

### LINKED ISSUE #102: Empty directory created by mock
I use moq with the following command line arguments:

```
moq -pkg mocknotifier -out ../notifier/mocknotifier/notifier.go . Notifier
```

If the target directory (`../notifier/mocknotifier`) already exists, this gets me the generated mock in the file `../notifier/mocknotifier/notifier.go` with the correct package name (`mocknotifier`).
But, additionally I get a directory `../mocknotifier`.

If the target directory does not exist, `moq` fails with the error message `open ../notifier/mocknotifier/notifier.go: no such file or directory`.

It looks like the creation of the target directory in https://github.com/matryer/moq/blob/master/pkg/moq/moq.go#L85 is somehow wrong since https://github.com/matryer/moq/commit/e17abc4d5d5ef928c640e8286db483519fbdd7fb.

After looking at the code again, the problem becomes obvious: the `MkDir` in https://github.com/matryer/moq/blob/master/pkg/moq/moq.go#L85 does not respect the `-out` flag.

### LINKED ISSUE #103: Failing to generate mocks on 1.13
This command works with go 1.12:

```bash
$ moq -out mocks/client.mock.go -pkg mocks ../../vendor/github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface ACMPCAAPI
```
but breaks badly with go 1.13:
```bash
$ moq -out mocks/client.mock.go -pkg mocks ../../vendor/github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface ACMPCAAPI
Couldn't load mock package: go [list -e -json -compiled -test=false -export=false -deps=false -find=true --]: exit status 1: build .: cannot find module for path .

moq [flags] destination interface [interface2 [interface3 [...]]]
  -out string
        output file (default stdout)
  -pkg string
        package name (default will infer)
```

Same version of `moq` in both cases, `github.com/matryer/moq v0.0.0-20190312154309-6cfb0558e1bd`, e.g., current master.

### PR DESCRIPTION
**Pull request by pdrum**
This fixes #103 and also fixes #102

### CODE REVIEW

**Comment by pdrum** [comment]
`packages.Load` in `golang.org/x/tools/go/packages` fails in go 1.9.X and 1.10.X  with an error like:

```
unsupported version of go: exit status 2: flag provided but not defined: -compiled
```

therefore I removed them from travis CI. Similar discussions can be found [here](https://github.com/dominikh/go-tools/issues/432) and [here](https://github.com/matryer/moq/pull/100#issuecomment-488798007). 

I added go 1.13 to travis too.

File: pkg/moq/moq.go [hunk 1]
```diff
@@ -98,12 +87,44 @@ func New(src, packageName string) (*Mocker, error) {
...
 		tmpl:    tmpl,
 		srcPkg:  srcPkg,
-		pkgName: packageName,
+		pkgName: preventZeroStr(packageName, srcPkg.Name),
 		pkgPath: pkgPath,
 		imports: make(map[string]bool),
 	}, nil
 }
 
+func preventZeroStr(val string, defaultVal string) string {
```
[the remark this answers is not in the document]
Comment (pdrum) [reply pkg/moq/moq.go]: I fixed this and force pushed in order to keep history clean

**Comment by pdrum** [comment]
By the way the reason for failure with go 1.13 was very similar to the reason empty directories were created. `pkgPath` was inferred incorrectly. I made [a repo](https://github.com/pdrum/moq-go-113) illustrating the issue. With go 1.13.

For the given scenario, second call to `pkgInfoFromPath` in `New` function of `moq.go` failed with the message:

```
Couldn't load mock package: go [list -e -json -compiled -test=false -export=false -deps=false -find=true --]: exit status 1: build .: cannot find module for path .
```

The reason why this happened is that in second call to `pkgInfoFromPath`, `src` had a value of `../foo/mocks`, the folder was just created (the bug regarding creation of empty directory) and therefore empty. this call caused the  error.

My solution was to 
* Never create the empty directory.
* If the directory in which the command has executed is a valid go package and its name matches the name given as `-pkg`, that directory is set as `pkgPath`
* Else if the package in which the interface resides is the same as what is given as `-pkg`, that dir is considered as `pkgPath` 
* Else if in the package containing the interface, there is a subdirectory with the same name as value of `-pkg` flag, that is set as the value of `pkgPath`
* Otherwise `pkgPath` is set to zero and `packageQualifier` never returns `""`

**Comment by pdrum** [comment]
@matryer @breml Will you consider taking a look at this please?

**Comment by thoeni** [comment]
LGTM 👍 - it'd be great to get this merged to unleash the full power of Go 1.13

**Comment by sudo-suhas** [comment]
Please note that it might be necessary to delete empty folders inside `pkg/moq/testpackages/example` for those who have the repo cloned prior to this merge.

**Comment by iamfortune** [comment]
So how do i fix this error cos i still get it on my VS code

**Comment by sudo-suhas** [comment]
Try updating the `moq` binary which is installed on your system. 

```
$ go get -u github.com/matryer/moq
```

You might need to run this outside of a Go module project or add the `GO11MODULE=off` flag while running the command.
