### ISSUE TITLE
Failing to generate mocks on 1.13

### ISSUE THREAD

**Issue by johanbrandhorst** [matryer/moq#103]
This command works with go 1.12:

```bash
$ moq -out mocks/client.mock.go -pkg mocks ../../vendor/github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface ACMPCAAPI
```
but breaks badly with go 1.13:
```bash
$ moq -out mocks/client.mock.go -pkg mocks ../../vendor/github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface ACMPCAAPI
Couldn't load mock package: go [list -e -json -compiled -test=false -export=false -deps=false -find=true --]: exit status 1: build .: cannot find module for path .

moq [flags] destination interface [interface2 [interface3 [...]]]
  -out string
        output file (default stdout)
  -pkg string
        package name (default will infer)
```

Same version of `moq` in both cases, `github.com/matryer/moq v0.0.0-20190312154309-6cfb0558e1bd`, e.g., current master.

**Comment by johanbrandhorst** [comment]
The examples are from running `go generate` in https://github.com/johanbrandhorst/certify/tree/master/issuers/aws. There seems to be something about the aws interface that breaks it.

**Comment by Agronis** [comment]
I might suggest importing the interface and assigning it to a new type local to that package, it is what I am doing with the `/service/s3/s3iface` interface

```
package main

import "github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface"

//go:generate moq -out s3_moq_test.go . MockAPI
type MockAPI = acmpcaiface.ClientAPI
```

Tested, and this generates with ease.

**Comment by johanbrandhorst** [comment]
Cool, thanks for the workaround!

**Comment by fredbi** [comment]
@johanbrandhorst had the same problem, but it did work with go1.13 on local dev, while repeatedly failing on CI. My guess is that the version of "golang.org/x/tools" package is subtly modified (see also #98).

The problem appears specifically when using the `-pkg`  option.

As a workaround for the "go list..." issue complaining that the mocked package is not here, I prepared an empty valid go file just for this to pass.
``` 
mkdir -p {mockpackage}
echo "package {mockpackage}" > {generated}.go
```

**Comment by johanbrandhorst** [comment]
> I might suggest importing the interface and assigning it to a new type local to that package, it is what I am doing with the `/service/s3/s3iface` interface
> 
> ```
> package main
> 
> import "github.com/aws/aws-sdk-go-v2/service/acmpca/acmpcaiface"
> 
> //go:generate moq -out s3_moq_test.go . MockAPI
> type MockAPI = acmpcaiface.ClientAPI
> ```

This is unfortunately unacceptable as it changes the public API of the package. It seems I will have to keep using 1.12 for now.

**Comment by pdrum** [comment]
I'm having the same issue
